import type { Metadata } from "next";
import { TranslationProvider } from "../lib/hooks/TranslationProvider";
import { swedish } from "../translations/swedish";
import { TrackingProvider } from "../lib/hooks/TrackingContext";
import { GroupDesignerProvider } from "../lib/hooks/GroupDesignerProvider";
import { CompareProvider } from "../lib/hooks/CompareProvider";
import { NotificationsProvider } from "../components/ui-notifications/notifications-provider";
import "./globals.css"; // Adjust path to your global stylesheet
import { SidebarMenu } from "../components/SidebarMenu";
import { MiniCart } from "../components/MiniCart";
import { CompareOverlay } from "../components/CompareOverlay";

export const metadata: Metadata = {
  title: "Slask Finder UI", // Replace with your app's title
  description: "Generated by create next app", // Replace with your app's description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TranslationProvider language={swedish}>
          <TrackingProvider>
            <GroupDesignerProvider>
              <NotificationsProvider>
                <CompareProvider compareAllFacets={true}>
                  <SidebarMenu />
                  <MiniCart />
                  {children}
                  <CompareOverlay />
                </CompareProvider>
              </NotificationsProvider>
            </GroupDesignerProvider>
          </TrackingProvider>
        </TranslationProvider>
      </body>
    </html>
  );
}
